import React from 'react';
import { Outlet, useLocation } from 'react-router-dom';
import { Sidebar, TopBar } from '@medisync/ui';
import { LayoutDashboard, Users, ShieldAlert, History, User } from 'lucide-react';
import { useAuthStore } from '../store/authStore';

export const DoctorLayout: React.FC = () => {
  const { user, logout } = useAuthStore();
  const location = useLocation();

  const navItems = [
    { label: 'Overview', path: '/dashboard', icon: <LayoutDashboard size={18} /> },
    { label: 'Patient Directory', path: '/patients', icon: <Users size={18} /> },
    { label: 'EHR OTP Gating', path: '/ehr', icon: <ShieldAlert size={18} /> },
    { label: 'Session Logs', path: '/sessions', icon: <History size={18} /> },
    { label: 'My Profile', path: '/profile', icon: <User size={18} /> },
  ];

  const getPageMeta = () => {
    switch (location.pathname) {
      case '/dashboard':
        return { title: 'Clinical Overview', subtitle: 'Overview of hospital and prescription metrics' };
      case '/patients':
        return { title: 'Patient Directory', subtitle: 'Search and inspect registered patient records' };
      case '/ehr':
        return { title: 'EHR Access Verification', subtitle: 'Secure verification of OTP generated by patient client' };
      case '/sessions':
        return { title: 'Clinical Sessions', subtitle: 'Review historical diagnosis and observation sessions' };
      case '/profile':
        return { title: 'Doctor Profile', subtitle: 'Clinical contact parameters and preferences' };
      default:
        return { title: 'EHR Record Viewer', subtitle: 'Inspect patient medical parameters' };
    }
  };

  const meta = getPageMeta();

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: 'var(--bg-base)' }}>
      <Sidebar
        navItems={navItems}
        user={user}
        onLogout={logout}
        accentColor="#059669"
      />
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
        <TopBar
          title={meta.title}
          subtitle={meta.subtitle}
          user={user}
        />
        <main style={{ flex: 1, padding: '28px', overflowY: 'auto' }}>
          <Outlet />
        </main>
      </div>
    </div>
  );
};
